version: '2.0'
config:
  store_entities_as_slots: true
session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true
intents: []
entities: []
slots: {}
responses: {}
actions:
- actions/**/*
- Dockerfile
forms: {}
e2e_actions: []
