language: python
sudo: required
services:
- docker
python:
  - '3.6'
before_install:
- python -m pip install -U pip
- pip install -e . --no-use-pep517
- export DISPLAY=0.0
- make train-memo
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
- make evaluate-core
- openssl aes-256-cbc -K $encrypted_8857e34a5e52_key -iv $encrypted_8857e34a5e52_iv
  -in travis_gcloud_auth.json.enc -out travis_gcloud_auth.json -d
- docker login -u _json_key -p "$(cat travis_gcloud_auth.json)" https://gcr.io
- docker pull gcr.io/replicated-test/rasa-demo:latest || true
script:
- docker build --build-arg GITHUB_TOKEN=${GITHUB_TOKEN} -t gcr.io/replicated-test/rasa-demo:v$TRAVIS_BUILD_NUMBER
  -t gcr.io/replicated-test/rasa-demo:latest --cache-from gcr.io/replicated-test/rasa-demo:latest
  .
- docker push gcr.io/replicated-test/rasa-demo:v$TRAVIS_BUILD_NUMBER
- docker push gcr.io/replicated-test/rasa-demo:latest
addons:
  ssh_known_hosts:
  - 35.206.176.121
  - website-demo.rasa.com
